export const PlayerActions = Object.freeze({
    PLAYER_REGISTRATION: "PLAYER_REGISTRATION",
    PLAYER_LOGIN: "PLAYER_LOGIN",
    GET_ALL_PLAYERS: "GET_ALL_PLAYERS"
})

export const SlotActions = Object.freeze({
    FILTERING_SLOTS: "FILTERING_SLOTS",
    GET_COURT_SLOT_INFO: "GET_COURT_SLOT_INFO",
    CREATE_GROUP: "CREATE_GROUP",
    DIRECT_BOOK: "DIRECT_BOOK"
})

